import SerreMarkov.PositiveThreeTerminalUpToEight
#print axioms SerreMarkov.PositiveThreeSix.a_three_d_six_bounds
#print axioms SerreMarkov.PositiveThreeSeven.a_three_d_seven_bounds
#print axioms SerreMarkov.PositiveThreeEight.a_three_d_eight_bounds
#print axioms SerreMarkov.PositiveThreeSix.a_three_d_six_terminal_classification
#print axioms SerreMarkov.PositiveThreeSeven.a_three_d_seven_terminal_classification
#print axioms SerreMarkov.PositiveThreeEight.a_three_d_eight_terminal_impossible
#print axioms SerreMarkov.PositiveThreeTerminalUpToEight.end_three_middle_upto_eight_terminal_bounded
#print axioms SerreMarkov.PositiveThreeTerminalUpToEight.end_three_middle_upto_eight_terminal_classification
