import SerreMarkov.PositiveIntegral
import Mathlib.LinearAlgebra.Matrix.SpecialLinearGroup
import Mathlib.LinearAlgebra.Matrix.ProjectiveSpecialLinearGroup
import Mathlib.Algebra.Group.Subgroup.Ker
import Mathlib.GroupTheory.QuotientGroup.Basic

/-!
# The actual even half-turn group and its integer realization

The even group is the subgroup generated by products of two actual half-turn
lifts. The common conjugation constructed from the Euler lattice acts on this
whole subgroup, not only on a list of selected matrices. No finite-index,
properness, fundamental-domain, or degree assumption is used here.
-/

namespace SerreMarkov.PositiveGroups

open RationalClifford CliffordOrder IntrinsicFrame
open scoped MatrixGroups

abbrev RealSL2 := SL(2, ℝ)
abbrev IntegerSL2 := SL(2, ℤ)
abbrev RealPSL2 := PSL(2, ℝ)
abbrev IntegerPSL2 := PSL(2, ℤ)

noncomputable def halfTurn (D : NormedClifford.Data) (i : Fin 4) : RealSL2 :=
  ⟨generator (NormedClifford.generators D) i, NormedClifford.generator_determinant D i⟩

noncomputable def liftedWord (D : NormedClifford.Data) (w : List (Fin 4)) : RealSL2 :=
  ⟨wordProduct (NormedClifford.generators D) w, NormedClifford.word_determinant D w⟩

/-- The lifted even group, generated by the sixteen pair products. Individual
half-turns are not asserted to lie in the integer group. -/
noncomputable def evenGroup (D : NormedClifford.Data) : Subgroup RealSL2 :=
  Subgroup.closure (Set.range (fun ij : Fin 4 × Fin 4 => halfTurn D ij.1 * halfTurn D ij.2))

theorem pair_mem_evenGroup (D : NormedClifford.Data) (i j : Fin 4) :
    halfTurn D i * halfTurn D j ∈ evenGroup D :=
  Subgroup.subset_closure ⟨(i,j),rfl⟩

theorem liftedWord_pair_cons (D : NormedClifford.Data) (i j : Fin 4) (w : List (Fin 4)) :
    liftedWord D (i :: j :: w) = (halfTurn D i * halfTurn D j) * liftedWord D w := by
  apply Subtype.ext
  exact (mul_assoc _ _ _).symm

/-- Every actual even word lies in the subgroup generated by pair products. -/
theorem even_word_mem_evenGroup (D : NormedClifford.Data) (w : List (Fin 4))
    (hw : Even w.length) : liftedWord D w ∈ evenGroup D := by
  induction w using List.twoStepInduction with
  | nil => exact (evenGroup D).one_mem
  | singleton i => simp at hw
  | cons_cons i j w ih =>
      rw [liftedWord_pair_cons]
      apply (evenGroup D).mul_mem (pair_mem_evenGroup D i j)
      apply ih
      simpa [List.length_cons, Nat.even_add_one] using hw

def integerCast : IntegerSL2 →* RealSL2 :=
  Matrix.SpecialLinearGroup.map (Int.castRingHom ℝ)

theorem integerCast_injective : Function.Injective integerCast :=
  Matrix.SpecialLinearGroup.map_intCast_injective

/-- The real matrix group image of the actual determinant-one integer group. -/
def integerImage : Subgroup RealSL2 := integerCast.range

noncomputable def conjugation (C Cinv : RatMat2) (hCC : C*Cinv = 1) (hIC : Cinv*C = 1) :
    RealSL2 ≃* RealSL2 where
  toFun g := ⟨rationalMatrixCast Cinv * (g : RealMat2) * rationalMatrixCast C, by
    have hdet : (rationalMatrixCast Cinv).det * (rationalMatrixCast C).det = 1 := by
      simpa only [map_mul, map_one, Matrix.det_mul, Matrix.det_one] using
        congrArg Matrix.det (congrArg rationalMatrixCast hIC)
    simpa only [Matrix.det_mul, g.property, mul_one] using hdet⟩
  invFun g := ⟨rationalMatrixCast C * (g : RealMat2) * rationalMatrixCast Cinv, by
    have hdet : (rationalMatrixCast C).det * (rationalMatrixCast Cinv).det = 1 := by
      simpa only [map_mul, map_one, Matrix.det_mul, Matrix.det_one] using
        congrArg Matrix.det (congrArg rationalMatrixCast hCC)
    simpa only [Matrix.det_mul, g.property, mul_one] using hdet⟩
  left_inv g := by
    apply Subtype.ext
    change rationalMatrixCast C * (rationalMatrixCast Cinv * (g : RealMat2) *
      rationalMatrixCast C) * rationalMatrixCast Cinv = (g : RealMat2)
    have hc : rationalMatrixCast C * rationalMatrixCast Cinv = (1 : RealMat2) := by
      rw [← map_mul, hCC, map_one]
    simp only [← mul_assoc, hc, one_mul]
    rw [mul_assoc, hc, mul_one]
  right_inv g := by
    apply Subtype.ext
    change rationalMatrixCast Cinv * (rationalMatrixCast C * (g : RealMat2) *
      rationalMatrixCast Cinv) * rationalMatrixCast C = (g : RealMat2)
    have hc : rationalMatrixCast Cinv * rationalMatrixCast C = (1 : RealMat2) := by
      rw [← map_mul, hIC, map_one]
    simp only [← mul_assoc, hc, one_mul]
    rw [mul_assoc, hc, mul_one]
  map_mul' g h := by
    apply Subtype.ext
    change rationalMatrixCast Cinv * ((g : RealMat2) * (h : RealMat2)) *
        rationalMatrixCast C =
      (rationalMatrixCast Cinv * (g : RealMat2) * rationalMatrixCast C) *
        (rationalMatrixCast Cinv * (h : RealMat2) * rationalMatrixCast C)
    have hc : rationalMatrixCast C * rationalMatrixCast Cinv = (1 : RealMat2) := by
      rw [← map_mul, hCC, map_one]
    simp only [mul_assoc]
    rw [← mul_assoc (rationalMatrixCast C) (rationalMatrixCast Cinv), hc, one_mul]

/-- Arithmetic integerization extends to the entire actual even subgroup. -/
theorem evenGroup_integer_conjugation (D : NormedClifford.Data) :
    ∃ (C Cinv : RatMat2) (hCC : C*Cinv = 1) (hIC : Cinv*C = 1),
      0 < C.det ∧ (evenGroup D).map (conjugation C Cinv hCC hIC).toMonoidHom ≤
        integerImage := by
  obtain ⟨C,Cinv,hpos,hCC,hIC,hwords⟩ :=
    normalized_even_words_integral_SL2_positive_conjugation D
  refine ⟨C,Cinv,hCC,hIC,hpos,?_⟩
  apply Subgroup.map_le_iff_le_comap.mpr
  apply (Subgroup.closure_le _).mpr
  rintro _ ⟨⟨i,j⟩,rfl⟩
  obtain ⟨Z,hZd,hZ⟩ := hwords [i,j] (by simp)
  refine ⟨⟨Z,hZd⟩, ?_⟩
  apply Subtype.ext
  change Z.map (Int.cast : ℤ → ℝ) = rationalMatrixCast Cinv *
    (generator (NormedClifford.generators D) i * generator (NormedClifford.generators D) j) *
      rationalMatrixCast C
  simpa [wordProduct] using hZ.symm

/-- The lifted even group is isomorphic to an actual subgroup of `SL₂(ℤ)`.
The statement makes no assertion about the index of this subgroup. -/
theorem evenGroup_isomorphic_integer_subgroup (D : NormedClifford.Data) :
    ∃ H : Subgroup IntegerSL2, Nonempty (evenGroup D ≃* H) := by
  obtain ⟨C,Cinv,hCC,hIC,_,hle⟩ := evenGroup_integer_conjugation D
  let e := conjugation C Cinv hCC hIC
  let K := (evenGroup D).map e.toMonoidHom
  let H := K.comap integerCast
  have heq : H.map integerCast = K := Subgroup.map_comap_eq_self hle
  let e1 : evenGroup D ≃* K := e.subgroupMap (evenGroup D)
  let e2 : H ≃* K := (H.equivMapOfInjective integerCast integerCast_injective).trans
    (MulEquiv.subgroupCongr heq)
  exact ⟨H,⟨e1.trans e2.symm⟩⟩

/-- This subgroup construction applies to each actual positive regular
solution, with its intrinsic extracted half-turn data. -/
theorem positive_solution_integer_subgroup (z : Six) (hz : isSolution z)
    (hreg : shiftedSerre z ^ 3 ≠ 0) (hpos : 0 < IntrinsicSigns.thirdMinorSum z) :
    ∃ (R : Frame z) (hA : 0 < A R) (H : Subgroup IntegerSL2),
      Nonempty (evenGroup (positiveHalfTurnData R hA) ≃* H) := by
  obtain ⟨R⟩ := solution_regular_has_frame z hz hreg
  have hA := (IntrinsicSigns.frame_thirdMinorSum_pos_iff R).mp hpos
  obtain ⟨H,hH⟩ := evenGroup_isomorphic_integer_subgroup (positiveHalfTurnData R hA)
  exact ⟨R,hA,H,hH⟩

def projective : RealSL2 →* RealPSL2 := QuotientGroup.mk' _

def integerProjective : IntegerSL2 →* RealPSL2 := projective.comp integerCast

theorem integerCast_mem_center_iff (g : IntegerSL2) :
    integerCast g ∈ Subgroup.center RealSL2 ↔ g ∈ Subgroup.center IntegerSL2 := by
  constructor
  · intro hg
    apply Subgroup.mem_center_iff.mpr
    intro h
    apply integerCast_injective
    simpa only [map_mul] using (Subgroup.mem_center_iff.mp hg (integerCast h))
  · intro hg
    obtain ⟨r,hr,hmat⟩ := Matrix.SpecialLinearGroup.mem_center_iff.mp hg
    apply Matrix.SpecialLinearGroup.mem_center_iff.mpr
    refine ⟨(r : ℝ), ?_, ?_⟩
    · exact_mod_cast hr
    · have hh := congrArg (fun M : Matrix (Fin 2) (Fin 2) ℤ => M.map (Int.cast : ℤ → ℝ)) hmat
      change Matrix.scalar (Fin 2) (r : ℝ) = (g : Matrix (Fin 2) (Fin 2) ℤ).map Int.cast
      simpa only [Matrix.scalar_apply, Matrix.diagonal_map (Int.cast_zero : (Int.cast : ℤ → ℝ) 0 = 0)] using hh

theorem integerProjective_ker : integerProjective.ker = Subgroup.center IntegerSL2 := by
  ext g
  change (QuotientGroup.mk (integerCast g) : RealPSL2) = 1 ↔ _
  rw [QuotientGroup.eq_one_iff]
  exact integerCast_mem_center_iff g

/-- The integer matrix image in the real projective group is the actual
`PSL₂(ℤ)` of Mathlib, via the first isomorphism theorem. -/
noncomputable def integerProjectiveEquiv : IntegerPSL2 ≃* integerProjective.range :=
  (QuotientGroup.quotientMulEquivOfEq integerProjective_ker.symm).trans
    (QuotientGroup.quotientKerEquivRange integerProjective)

noncomputable def integerPSLCast : IntegerPSL2 →* RealPSL2 :=
  integerProjective.range.subtype.comp integerProjectiveEquiv.toMonoidHom

theorem integerPSLCast_injective : Function.Injective integerPSLCast :=
  Subtype.val_injective.comp integerProjectiveEquiv.injective

theorem integerPSLCast_range : integerPSLCast.range = integerProjective.range := by
  ext g
  constructor
  · rintro ⟨x,rfl⟩
    exact (integerProjectiveEquiv x).property
  · intro hg
    refine ⟨integerProjectiveEquiv.symm ⟨g,hg⟩,?_⟩
    exact congrArg Subtype.val (integerProjectiveEquiv.apply_symm_apply ⟨g,hg⟩)

/-- The actual conjugated projective even group is the image of an actual
subgroup of `PSL₂(ℤ)`. Its finite index is a separate unproved conclusion. -/
theorem evenGroup_integer_projective_subgroup (D : NormedClifford.Data) :
    ∃ (C Cinv : RatMat2) (hCC : C*Cinv = 1) (hIC : Cinv*C = 1)
      (H : Subgroup IntegerPSL2), 0 < C.det ∧
      H.map integerPSLCast =
        (evenGroup D).map (projective.comp (conjugation C Cinv hCC hIC).toMonoidHom) := by
  obtain ⟨C,Cinv,hCC,hIC,hpos,hle⟩ := evenGroup_integer_conjugation D
  let K := (evenGroup D).map (projective.comp (conjugation C Cinv hCC hIC).toMonoidHom)
  have hk : K ≤ integerPSLCast.range := by
    rw [integerPSLCast_range]
    rintro g ⟨x,hx,rfl⟩
    obtain ⟨Z,hZ⟩ := hle (Subgroup.mem_map.mpr ⟨x,hx,rfl⟩)
    refine ⟨Z,?_⟩
    exact congrArg projective hZ
  refine ⟨C,Cinv,hCC,hIC,K.comap integerPSLCast,hpos,?_⟩
  exact Subgroup.map_comap_eq_self hk

theorem positive_solution_integer_projective_subgroup (z : Six) (hz : isSolution z)
    (hreg : shiftedSerre z ^ 3 ≠ 0) (hpos : 0 < IntrinsicSigns.thirdMinorSum z) :
    ∃ (R : Frame z) (hA : 0 < A R) (C Cinv : RatMat2)
      (hCC : C*Cinv = 1) (hIC : Cinv*C = 1) (H : Subgroup IntegerPSL2),
      0 < C.det ∧ H.map integerPSLCast =
        (evenGroup (positiveHalfTurnData R hA)).map
          (projective.comp (conjugation C Cinv hCC hIC).toMonoidHom) := by
  obtain ⟨R⟩ := solution_regular_has_frame z hz hreg
  have hA := (IntrinsicSigns.frame_thirdMinorSum_pos_iff R).mp hpos
  obtain ⟨C,Cinv,hCC,hIC,H,hpositive,hH⟩ :=
    evenGroup_integer_projective_subgroup (positiveHalfTurnData R hA)
  exact ⟨R,hA,C,Cinv,hCC,hIC,H,hpositive,hH⟩

end SerreMarkov.PositiveGroups
