import SerreMarkov.ReflectionGroup
import Mathlib.Algebra.BigOperators.Group.List.Basic

/-! # Words in a subgroup generated by involutions

Every element of the closure is a finite product of the named generators.
Reversing a word gives its inverse, because each generator is involutive.
The specialization below uses the actual integral reflection units.
-/

namespace SerreMarkov.ReflectionWords

/-- Products are taken from left to right in the displayed word. -/
def wordProduct {ι G : Type*} [Monoid G] (R : ι → G) (w : List ι) : G :=
  (w.map R).prod

@[simp] theorem wordProduct_nil {ι G : Type*} [Monoid G] (R : ι → G) :
    wordProduct R [] = 1 := rfl

@[simp] theorem wordProduct_cons {ι G : Type*} [Monoid G]
    (R : ι → G) (i : ι) (w : List ι) :
    wordProduct R (i::w) = R i * wordProduct R w := rfl

@[simp] theorem wordProduct_append {ι G : Type*} [Monoid G]
    (R : ι → G) (w v : List ι) :
    wordProduct R (w++v) = wordProduct R w * wordProduct R v := by
  simp only [wordProduct, List.map_append, List.prod_append]

/-- Word reversal is inversion when the generators are involutions. -/
theorem wordProduct_reverse {ι G : Type*} [Group G] (R : ι → G)
    (hinv : ∀ i, (R i)⁻¹ = R i) (w : List ι) :
    wordProduct R w.reverse = (wordProduct R w)⁻¹ := by
  simpa only [wordProduct, List.map_reverse, List.map_map, Function.comp_def, hinv] using
    List.prod_reverse_noncomm (w.map R)

theorem wordProduct_mem_closure {ι G : Type*} [Group G]
    (R : ι → G) (w : List ι) : wordProduct R w ∈ Subgroup.closure (Set.range R) := by
  induction w with
  | nil => exact Subgroup.one_mem _
  | cons i w ih =>
    rw [wordProduct_cons]
    exact Subgroup.mul_mem _ (Subgroup.subset_closure ⟨i,rfl⟩) ih

/-- Closure induction extracts an ordinary generator word, with no inverse
letters needed for involutive generators. -/
theorem closure_word_exists {ι G : Type*} [Group G] (R : ι → G)
    (hinv : ∀ i, (R i)⁻¹ = R i) (x : G)
    (hx : x ∈ Subgroup.closure (Set.range R)) :
    ∃ w : List ι, wordProduct R w = x := by
  refine Subgroup.closure_induction (p := fun x _ => ∃ w, wordProduct R w = x)
    ?_ ?_ ?_ ?_ hx
  · rintro x ⟨i,rfl⟩
    exact ⟨[i], by simp⟩
  · exact ⟨[], rfl⟩
  · intro a b _ _ ha hb
    obtain ⟨wa,rfl⟩ := ha
    obtain ⟨wb,rfl⟩ := hb
    exact ⟨wa++wb, wordProduct_append R wa wb⟩
  · intro a _ ha
    obtain ⟨w,rfl⟩ := ha
    exact ⟨w.reverse, wordProduct_reverse R hinv w⟩

theorem mem_closure_iff_word {ι G : Type*} [Group G] (R : ι → G)
    (hinv : ∀ i, (R i)⁻¹ = R i) (x : G) :
    x ∈ Subgroup.closure (Set.range R) ↔ ∃ w : List ι, wordProduct R w = x := by
  constructor
  · exact closure_word_exists R hinv x
  · rintro ⟨w,rfl⟩
    exact wordProduct_mem_closure R w

open ReflectionGroup

/-- Every actual integral reflection-group element admits a generator word. -/
theorem reflectionGroup_word_exists (z : Six) (U : Mat4ˣ)
    (hU : U ∈ reflectionGroup z) :
    ∃ w : List (Fin 4), (w.map (reflectionUnit z)).prod = U :=
  closure_word_exists (reflectionUnit z) (reflectionUnit_inv z) U hU

theorem reflection_word_mem (z : Six) (w : List (Fin 4)) :
    (w.map (reflectionUnit z)).prod ∈ reflectionGroup z :=
  wordProduct_mem_closure (reflectionUnit z) w

theorem reflectionGroup_mem_iff_word (z : Six) (U : Mat4ˣ) :
    U ∈ reflectionGroup z ↔ ∃ w : List (Fin 4), (w.map (reflectionUnit z)).prod = U :=
  mem_closure_iff_word (reflectionUnit z) (reflectionUnit_inv z) U

/-- Reversing the extracted reflection word gives its inverse unit. -/
theorem reflection_word_reverse (z : Six) (w : List (Fin 4)) :
    (w.reverse.map (reflectionUnit z)).prod = ((w.map (reflectionUnit z)).prod)⁻¹ :=
  wordProduct_reverse (reflectionUnit z) (reflectionUnit_inv z) w

/-- The unit word has the expected product as its integral matrix value. -/
theorem reflection_word_matrix (z : Six) (w : List (Fin 4)) :
    ((w.map (reflectionUnit z)).prod : Mat4) = (w.map (basisReflection z)).prod := by
  induction w with
  | nil => rfl
  | cons i w ih => simp only [List.map_cons, List.prod_cons, Units.val_mul,
      reflectionUnit_val, ih]

end SerreMarkov.ReflectionWords
