"""Emit kernel proofs from independently recovered exact positive certificates.

The temporary input files are generated by the scratch search. Permanent
certificate data are saved alongside this emitter before Lean source is written.
"""
from pathlib import Path
from fractions import Fraction
from math import lcm
from collections import defaultdict
import pickle,json

ROOT=Path(__file__).resolve().parents[1]
CERTDIR=ROOT/'scripts'/'certificates'
CERTDIR.mkdir(exist_ok=True)
VARS=('A','B','C','D','E','F');ZERO=(0,)*6
def decode(p):return {tuple(m):Fraction(co) for m,co in p}
metafile=CERTDIR/'positive_sorted_large_guard_metadata.json'
if metafile.exists():
 saved=json.loads(metafile.read_text())
 metadata=dict(base={n:decode(p) for n,p in saved['base'].items()},
   factors=saved['factors'],needed=set(saved['needed']),metadata=saved['metadata'])
else:
 metadata=pickle.load(open('/tmp/positive_sorted_core_guard_metadata.pkl','rb'))
 saved=dict(base={n:[[list(m),str(co)] for m,co in metadata['base'][n].items()]
   for n in metadata['needed']},factors=metadata['factors'],needed=sorted(metadata['needed']),
   metadata={n:{k:v for k,v in info.items() if k!='raw'} for n,info in metadata['metadata'].items()})
 metafile.write_text(json.dumps(saved,indent=2))
needed=sorted(metadata['needed']);ids={name:i for i,name in enumerate(needed)}
ln='⟨A+6,B+3,A+C+D+6,A+D+6,E+3,A+F+6⟩'
args='A B C D E F'
params='(A B C D E F : ℤ)'
hyps='(hA : 0≤A) (hB : 0≤B) (hC : 0≤C) (hD : 0≤D) (hE : 0≤E) (hF : 0≤F)'
names=['m1','i1','m2','i2','m3','i3']
def word(w):return '['+','.join('.'+names[i] for i in w)+']'
def mono(m):return '*'.join(x if e==1 else f'{x}^{e}' for x,e in zip(VARS,m) if e) or '1'
def leanpoly(p):
 out=[]
 for m,co in sorted(p.items(),reverse=True):
  assert co.denominator==1 if isinstance(co,Fraction) else True
  co=int(co)
  if not co:continue
  term=str(abs(co)) if m==ZERO else f'{abs(co)}*{mono(m)}'
  out.append(('-' if co<0 else '+')+term)
 return ''.join(out).lstrip('+') or '0'
def add(p,q,scale=Fraction(1),shift=ZERO):
 out=dict(p)
 for m,c in q.items():
  ex=tuple(x+y for x,y in zip(m,shift));out[ex]=out.get(ex,0)+scale*c
  if not out[ex]:del out[ex]
 return out
def mul(p,q):
 out={}
 for m,c in p.items():out=add(out,q,c,m)
 return out
def key(m):return (sum(m),tuple(-i for i in reversed(m)))
def represent(residue,tracked):
 p=dict(residue);u={};w={};rem={}
 while p:
  m=max(p,key=key);co=p[m];hit=None
  for g,gu,gw in tracked['rules']:
   n=max(g,key=key)
   if all(x>=y for x,y in zip(m,n)):hit=(g,gu,gw,n);break
  if hit is None:rem[m]=co;del p[m];continue
  g,gu,gw,n=hit;shift=tuple(x-y for x,y in zip(m,n));fac=co/g[n]
  p=add(p,g,-fac,shift);u=add(u,gu,fac,shift);w=add(w,gw,fac,shift)
 assert not rem
 assert add(add({},mul(u,tracked['q1'])),mul(w,tracked['q2']))==residue
 return u,w
def encode(p):return [[list(m),str(c)] for m,c in sorted(p.items())]
def nonnegative_poly(p):
 proofs=[]
 for m,co in sorted(p.items(),reverse=True):
  co=int(co)
  if not co:continue
  assert co>0
  proof=f'(Int.natCast_nonneg {co})'
  for name,e in zip(VARS,m):
   if not e:continue
   factor=f'h{name}' if e==1 else f'(pow_nonneg h{name} {e})'
   proof=f'(mul_nonneg {proof} {factor})'
  proofs.append(proof)
 if not proofs:return '(le_refl (0:ℤ))'
 ans=proofs[0]
 for proof in proofs[1:]:ans=f'(add_nonneg {ans} {proof})'
 return ans
def add_proofs(proofs):
 ans=proofs[0]
 for p in proofs[1:]:ans=f'(add_nonneg {ans} {p})'
 return ans
def mul_proofs(proofs):
 ans=proofs[0]
 for p in proofs[1:]:ans=f'(mul_nonneg {ans} {p})'
 return ans

# Base guards are modest polynomial identities, compiled before the two large
# final coefficient identities. Their semantic proofs use actual braid words.
helper=ROOT/'SerreMarkov'/'PositiveSortedLargeGuards.lean'
if helper.exists():
 prefix=helper.read_text().split('set_option linter.unusedVariables false',1)[0]
else:
 prefix=(ROOT/'SerreMarkov'/'PositiveSortedLarge.lean').read_text().rsplit('end SerreMarkov.PositiveSortedLarge',1)[0]
prefix=prefix.replace('Nonnegative guards for the ordered large-edge terminal certificate.',
  'Nonnegative guards for the ordered large-edge terminal certificate.')
guards=[prefix,'set_option linter.unusedVariables false\n']
unfold='applyWord,step,mu1,mu2,mu3,inv1,inv2,inv3'
for name in needed:
 i=ids[name];p=metadata['base'][name];info=metadata['metadata'][name]
 assert info['normalizer']==1
 guards.append(f'\ndef guard{i} {params} : ℤ := {leanpoly(p)}\n')
 guards.append(f'theorem guard{i}_nonnegative {params}\n    {hyps}\n    (hz : Chamber {ln}) (ht : AllTerminal {ln}) :\n    0≤guard{i} {args} := by\n')
 kind=info['kind'];w=word(info.get('word',()))
 if kind in ('var','newvar'):
  guards.append(f'  dsimp only [guard{i}]\n  positivity\n')
 else:
  if kind=='height':
   raw=f'heightPolynomial {ln} {w}'
   guards.append(f'  have hr : 0≤{raw} := word_height_nonnegative _ hz ht {w} (by decide +kernel)\n')
   more='heightPolynomial,coordinateSum,'+unfold
  elif kind=='coord':
   field='abcdef'[info['index']];raw=f'(applyWord {ln} {w}).{field}-3'
   proj='.2'*info['index']+'.1' if info['index']<5 else '.2'*5
   guards.append(f'  have hc := word_coordinates _ hz {w} (by decide +kernel)\n  have hr : 0≤{raw} := by linarith only [hc{proj}]\n')
   more=unfold
  elif kind=='tri':
   coords=[('a','b','d'),('a','c','e'),('b','c','f'),('d','e','f')][info['index']]
   raw='-7-triangleDefect '+' '.join(f'(applyWord {ln} {w}).{field}' for field in coords)
   proj='.2'*info['index']+'.1' if info['index']<3 else '.2'*3
   guards.append(f'  have hc := word_triangle_bounds _ hz {w} (by decide +kernel)\n  have hr : 0≤{raw} := by linarith only [hc{proj}]\n')
   more='triangleDefect,'+unfold
  elif kind=='marker':
   raw=f'IntrinsicSigns.thirdMinorSum {ln}-2'
   guards.append(f'  have hr : 0≤{raw} := marker_nonnegative _ hz\n')
   more='IntrinsicSigns.thirdMinorSum'
  else:raise ValueError(kind)
  guards.append(f'  have heq : guard{i} {args}={raw} := by\n    dsimp only [guard{i},{more}]\n    ring\n  rw [heq]\n  exact hr\n')
guards.append('\nend SerreMarkov.PositiveSortedLarge\n')
guardfile=ROOT/'SerreMarkov'/'PositiveSortedLargeGuards.lean'
if not guardfile.exists() or guardfile.read_text()!=''.join(guards):
 guardfile.write_text(''.join(guards))

for label,sign in [('Minus',-4),('Plus',4)]:
 certfile=CERTDIR/('positive_sorted_large_'+label.lower()+'.json')
 if certfile.exists():
  certificate=json.loads(certfile.read_text());den=int(certificate['scale'])
  groups={n:decode(p) for n,p in certificate['guards'].items()}
  mu=decode(certificate['mu']);nu=decode(certificate['nu'])
 else:
  data=pickle.load(open('/tmp/positive_sorted_core_exact_'+label.lower()+'.pkl','rb'))
  source=data['source'];exact=data['exact'];tracked=pickle.load(open('/tmp/positive_sorted_gb_tracked_'+str(sign)+'.pkl','rb'))
  groups=defaultdict(dict);residue={ZERO:Fraction(1)}
  for j,co in exact.items():
   assert co>=0
   name,m,p=source['poslabel'][j]
   residue=add(residue,p,co,m)
   groups[name][m]=groups[name].get(m,0)+co
  mu,nu=represent(residue,tracked)
  # L+P-mu*q1-nu*q2=0; positivity makes the left constant impossible.
  den=lcm(*(co.denominator for p in list(groups.values())+[mu,nu] for co in p.values()))
  groups={n:{m:int(co*den) for m,co in p.items()} for n,p in groups.items()}
  mu={m:int(co*den) for m,co in mu.items()};nu={m:int(co*den) for m,co in nu.items()}
  certificate=dict(sign=sign,scale=str(den),guards={n:encode(p) for n,p in groups.items()},
   mu=encode(mu),nu=encode(nu),base={n:encode(metadata['base'][n]) for n in needed},
   factors={n:metadata['factors'][n] for n in groups})
  certfile.write_text(json.dumps(certificate,indent=2))
 lines=['import SerreMarkov.PositiveSortedLargeGuards\n\nnamespace SerreMarkov.PositiveSortedLarge\n',
  'open PositiveChamber PositiveShortWord PositiveSortedTerminal NegativeDescent\n',
  'set_option Elab.async false\nset_option maxHeartbeats 0\nset_option maxRecDepth 200000\n',
  f'\ntheorem certificate_{label.lower()} {params}\n    {hyps}\n    (hz : Chamber {ln}) (ht : AllTerminal {ln})\n    (hq : q2 {ln}={sign if sign>0 else "(-4)"}) : False := by\n']
 baseused=sorted({b for n in groups for b in metadata['factors'][n]})
 for base in baseused:
  i=ids[base]
  lines.append(f'  have hG{i} := guard{i}_nonnegative {args} hA hB hC hD hE hF hz ht\n')
 terms=[];defs=[]
 for j,(name,p) in enumerate(groups.items()):
  lines.append(f'  let M{j} : ℤ := {leanpoly(p)}\n  have hM{j} : 0≤M{j} := {nonnegative_poly(p)}\n')
  gs='*'.join(f'(guard{ids[b]} {args})' for b in metadata['factors'][name])
  gp=mul_proofs([f'hG{ids[b]}' for b in metadata['factors'][name]])
  lines.append(f'  let T{j} : ℤ := M{j}*({gs})\n  have hT{j} : 0≤T{j} := mul_nonneg hM{j} {gp}\n')
  terms.append(f'T{j}');defs.extend((f'T{j}',f'M{j}'))
 lines.append('  let P : ℤ := '+'+'.join(terms)+'\n  have hp : 0≤P := '+add_proofs([f'hT{j}' for j in range(len(terms))])+'\n')
 qsign='4' if sign>0 else '(-4)'
 lines.append(f'  have hid : {den}+P-({leanpoly(mu)})*(q1 {ln}-8)-({leanpoly(nu)})*(q2 {ln}-{qsign})=0 := by\n')
 lines.append('    dsimp only [P,'+','.join(defs)+','+','.join(f'guard{ids[b]}' for b in baseused)+',q1,q2]\n    clear * - A B C D E F\n    ring\n')
 lines.append(f'  have hzero : {den}+P=0 := by\n    simpa only [hz.1.1,hq,sub_self,mul_zero,sub_zero] using hid\n')
 lines.append(f'  have hpos : 0<{den}+P := add_pos_of_pos_of_nonneg (by norm_num) hp\n  exact (ne_of_gt hpos) hzero\n\nend SerreMarkov.PositiveSortedLarge\n')
 (ROOT/'SerreMarkov'/('PositiveSortedLarge'+label+'.lean')).write_text(''.join(lines))
 print(label,'groups',len(groups),'base',len(baseused),'mu',len(mu),'nu',len(nu),'scale digits',len(str(den)),flush=True)

main='''import SerreMarkov.PositiveSortedLargeMinus
import SerreMarkov.PositiveSortedLargePlus

/-! The first outer edge of every sorted terminal positive chamber is at most
five. This is proved from actual finite-word guards by exact integer identities.
-/
namespace SerreMarkov.PositiveSortedLarge
open PositiveChamber PositiveShortWord PositiveSortedTerminal

theorem sorted_first_ge_six_impossible (z : Six) (hz : Chamber z)
    (hs : SortedOuter z) (ht : AllTerminal z) (ha : 6≤z.a) : False := by
  let A := z.a-6
  let B := z.b-3
  let C := z.c-z.d
  let D := z.d-z.a
  let E := z.e-3
  let F := z.f-z.a
  have heq : z=⟨A+6,B+3,A+C+D+6,A+D+6,E+3,A+F+6⟩ := by
    ext <;> dsimp [A,B,C,D,E,F] <;> ring
  have hA : 0≤A := by dsimp [A]; omega
  have hB : 0≤B := by dsimp [B]; have h:=hz.2.2.2.1; omega
  have hC : 0≤C := by dsimp [C]; have h:=hs.2.2.2; omega
  have hD : 0≤D := by dsimp [D]; have h:=hs.2.1; omega
  have hE : 0≤E := by dsimp [E]; have h:=hz.2.2.2.2.2.2.1; omega
  have hF : 0≤F := by dsimp [F]; have h:=hs.2.2.1; omega
  have hw : Chamber ⟨A+6,B+3,A+C+D+6,A+D+6,E+3,A+F+6⟩ := heq ▸ hz
  have htw : AllTerminal ⟨A+6,B+3,A+C+D+6,A+D+6,E+3,A+F+6⟩ := heq ▸ ht
  have hq : q2 ⟨A+6,B+3,A+C+D+6,A+D+6,E+3,A+F+6⟩=4 ∨
      q2 ⟨A+6,B+3,A+C+D+6,A+D+6,E+3,A+F+6⟩= -4 :=
    sq_eq_sq_iff_eq_or_eq_neg.mp (by norm_num; exact hw.1.2)
  rcases hq with hq|hq
  · exact certificate_plus A B C D E F hA hB hC hD hE hF hw htw hq
  · exact certificate_minus A B C D E F hA hB hC hD hE hF hw htw hq

theorem sorted_first_edge_le_five (z : Six) (hz : Chamber z)
    (hs : SortedOuter z) (ht : AllTerminal z) : z.a≤5 := by
  by_contra hn
  exact sorted_first_ge_six_impossible z hz hs ht (by omega)

end SerreMarkov.PositiveSortedLarge
'''
(ROOT/'SerreMarkov'/'PositiveSortedLarge.lean').write_text(main)
