#!/usr/bin/env python3
"""Check every Blueprint \\lean reference in the compiled Lean environment.

Run from any directory.  Ordinary installations need no options.  Work Mode
may pass --lean-prefix ./tooling/with_lean.sh with the documented runtime env.
This generates a command-only audit file; it adds no mathematical declarations.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
from pathlib import Path
import re
import shlex
import subprocess
import sys


PROJECT = Path(__file__).resolve().parents[2]
BLUEPRINT = PROJECT / "blueprint"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def tex_references() -> tuple[dict[str, list[dict]], list[dict]]:
    paths = [BLUEPRINT / "src/content.tex"]
    paths.extend(sorted((BLUEPRINT / "src/chapters").glob("*.tex")))
    references: dict[str, list[dict]] = {}
    inputs = []
    for path in paths:
        raw = path.read_text(encoding="utf-8")
        # TeX comments do not contribute clickable references.
        cleaned = re.sub(r"(?<!\\)%[^\n]*", "", raw)
        inputs.append({"path": str(path.relative_to(PROJECT)), "sha256": sha256(path)})
        for match in re.finditer(r"\\lean\s*\{([^{}]*)\}", cleaned):
            line = cleaned.count("\n", 0, match.start()) + 1
            for name in match.group(1).split(","):
                name = name.strip()
                if not re.fullmatch(r"[A-Za-z_][A-Za-z_0-9'.]*", name):
                    raise ValueError(f"Unsupported declaration name {name!r} in {path}:{line}")
                references.setdefault(name, []).append({
                    "path": str(path.relative_to(PROJECT)), "line": line,
                })
    if not references:
        raise ValueError("No Blueprint Lean references found")
    return references, inputs


def lean_audit(names: list[str]) -> str:
    quoted = ",\n    ".join("`" + name for name in names)
    return f'''-- Generated by blueprint/scripts/verify_lean_refs.py; no mathematical declarations.
import SerreMarkov
import Lean.Util.CollectAxioms
import Lean.DeclarationRange

open Lean Elab Command

run_cmd do
  let names : Array Name := #[
    {quoted}]
  let env ← getEnv
  for n in names do
    let some ci := env.find? n | throwError "Missing Blueprint declaration {{n}}"
    let kind := match ci with
      | .thmInfo _ => "theorem"
      | .defnInfo _ => "definition"
      | .opaqueInfo _ => "opaque"
      | .axiomInfo _ => "axiom"
      | .inductInfo _ => "inductive"
      | .ctorInfo _ => "constructor"
      | .recInfo _ => "recursor"
      | .quotInfo _ => "quotient"
    let moduleName := match env.getModuleIdxFor? n with
      | some idx => env.header.moduleNames[idx]!.toString
      | none => "<current>"
    let ranges ← findDeclarationRanges? n
    let line := ranges.map (·.selectionRange.pos.line) |>.getD 0
    logInfo m!"BLUEPRINT_REF|{{n}}|{{moduleName}}|{{line}}|{{kind}}"
  let allowed : Array Name := #[`propext, `Classical.choice, `Quot.sound]
  let action : CollectAxioms.M Unit := do
    for n in names do
      CollectAxioms.collect n
  let (_, state) := (action.run env).run {{}}
  for a in state.axioms do
    unless allowed.contains a do
      throwError "Disallowed transitive axiom {{a}} in Blueprint references"
  logInfo m!"BLUEPRINT_ALLOWED_AXIOMS|{{state.axioms}}"
  logInfo m!"BLUEPRINT_AUDIT_PASSED|{{names.size}}"
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--lean-prefix", default="", help="Optional command prefix, e.g. ./tooling/with_lean.sh")
    args = parser.parse_args()
    refs, inputs = tex_references()
    out = BLUEPRINT / "verification"
    out.mkdir(parents=True, exist_ok=True)
    audit = out / "LeanReferenceAudit.lean"
    audit.write_text(lean_audit(sorted(refs)), encoding="utf-8")
    command = shlex.split(args.lean_prefix) + ["lake", "env", "lean", str(audit.relative_to(PROJECT))]
    completed = subprocess.run(command, cwd=PROJECT, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    log = out / "lean_references.log"
    log.write_text(completed.stdout, encoding="utf-8")
    entries = {}
    for match in re.finditer(r"BLUEPRINT_REF\|([^|\n]+)\|([^|\n]+)\|(\d+)\|([^\n]+)", completed.stdout):
        name, module, line, kind = match.groups()
        source = Path(module.replace(".", "/") + ".lean")
        path = PROJECT / source
        if not path.is_file():
            raise ValueError(f"Imported declaration {name} has no local source {source}")
        line_number = int(line)
        if not 1 <= line_number <= len(path.read_text(encoding="utf-8").splitlines()):
            raise ValueError(f"Compiler supplied no valid source position for {name}: {line}")
        entries[name] = {
            "name": name, "kind": kind, "module": module,
            "source": source.as_posix(), "line": line_number,
            "source_sha256": sha256(path), "blueprint_locations": refs[name],
        }
    count = re.search(r"BLUEPRINT_AUDIT_PASSED\|(\d+)", completed.stdout)
    passed = completed.returncode == 0 and count is not None and int(count.group(1)) == len(refs) and set(entries) == set(refs)
    report = {
        "generated_at_utc": dt.datetime.now(dt.timezone.utc).isoformat(),
        "passed": passed, "exit_code": completed.returncode,
        "unique_declarations": len(refs),
        "reference_occurrences": sum(map(len, refs.values())),
        "allowed_transitive_axioms": ["propext", "Classical.choice", "Quot.sound"],
        "axioms_used_log": next((line for line in completed.stdout.splitlines() if "BLUEPRINT_ALLOWED_AXIOMS|" in line), None),
        "command": command, "tex_inputs": inputs,
        "lean_audit_sha256": sha256(audit), "log_sha256": sha256(log),
        "declarations": [entries[name] for name in sorted(entries)],
    }
    (out / "lean_references.json").write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    if not passed:
        print(completed.stdout, file=sys.stderr)
        print("Blueprint reference audit FAILED", file=sys.stderr)
        return 1
    print(f"Blueprint reference audit PASSED: {len(refs)} declarations, {report['reference_occurrences']} references")
    print(f"Log: {log.relative_to(PROJECT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
